name: Bug report
description: Create a bug report to help us improve
title: '[BUG]: The WeMod launcher fails with error X'
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I was trying to [...]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to x
        2. Press button y
        3. Error comes up
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected [...]
    validations:
      required: true


  - type: textarea
    id: any-logs
    attributes:
      label: Logs
      description: Any logfile or teminal error output
      placeholder: drag wemod.log on here if missing use the teminal output of the steam command
    validations:
      required: true
      

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: system-information
    attributes:
      label: System Information
      description: Plese provide more information about your system
      placeholder: |
         * OS: [e.g. Ubuntu 20.04, Arch 2022.02.01]
         * Script version [e.g. 1.545]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other relevant information about the problem.
      placeholder: Add any other context about the problem here.
    validations:
      required: false
