name: Lint and Format Code

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install black

      - name: Checkout dev
        if: github.ref == 'refs/heads/dev'
        run: |
          # Checkout dev branch
          git checkout dev

      - name: Checkout main
        if: github.ref == 'refs/heads/main'
        run: |
          # Checkout main branch
          git checkout main
      
      - name: Run Black
        id: run_black
        run: |
          black -l 78 -t py312 ./*.py ./wemod

      - name: Commit changes on dev
        if: github.ref == 'refs/heads/dev' && steps.run_black.outcome == 'success'
        id: commit_changes_dev
        run: |
          # Commit changes
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Github actions automatic code formatting on dev branch' -m 'This is an automatic task, run by a GitHub workflow, to automatically format the Python code in the repo, with the code formatter "black"' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge dev into main
        if: github.ref == 'refs/heads/dev' && steps.commit_changes_dev.outcome == 'success'
        run: |
          # Run old code as well to sync merge reqests
          git fetch origin main
          git checkout main
          git pull origin main
          git merge dev --no-ff --strategy-option ours -m "Auto merge/sync branch 'dev' into 'main' (merge reqest sync)"
          git push origin dev

          git fetch origin dev
          git checkout dev
          git pull origin dev
          git merge main --no-ff --strategy-option ours -m "Auto pull/sync back changes from 'main' into 'dev' (merge reqest sync)"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes on main
        if: github.ref == 'refs/heads/main' && steps.run_black.outcome == 'success'
        id: commit_changes_main
        run: |
          # Commit changes
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Github actions automatic code formatting on main branch' -m 'This is an automatic task, run by a GitHub workflow, to automatically format the Python code in the repo, with the code formatter "black"' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Merge main into dev
        if: github.ref == 'refs/heads/main' && steps.commit_changes_main.outcome == 'success'
        run: |
          # Run old code as well to sync merge reqests
          git fetch origin dev
          git checkout dev
          git pull origin dev
          git merge main --no-ff --strategy-option ours -m "Auto pull/sync back changes from 'main' into 'dev' (merge reqest sync)"
          git push origin dev

          git fetch origin main
          git checkout main
          git pull origin main
          git merge dev --no-ff --strategy-option ours -m "Auto merge/sync branch 'dev' into 'main' (merge reqest sync)"
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
